import {
  type Departure,
  type GalleryImage,
  type ItineraryDay,
  type Tour,
  type TourSection,
} from "./schemas";

/**
 * Mock data used when GOOGLE_SHEETS_CREDENTIALS is missing or set to the
 * placeholder value. It mirrors the Google Sheets CMS schema so page work can
 * be built and tested before the client-owned Sheet is connected.
 */

const t = (es: string) => ({
  es,
  en: `${es}`,
  pt: `${es}`,
});

const empty = { es: "", en: "", pt: "" };

function galleryImage({
  tour_slug,
  sort_order,
  image_url,
  alt,
  featured = false,
}: {
  tour_slug: string;
  sort_order: number;
  image_url: string;
  alt: string;
  featured?: boolean;
}): GalleryImage {
  return {
    tour_slug,
    sort_order,
    image_url,
    image_drive_id: "",
    alt: t(alt),
    caption: empty,
    featured,
  };
}

function highlights(items: string[]): ItineraryDay["highlights"] {
  return {
    es: items,
    en: items.map((item) => `${item}`),
    pt: items.map((item) => `${item}`),
  };
}

function itineraryDay({
  tour_slug,
  day_number,
  title,
  route_from,
  route_to,
  distance_km,
  surface,
  max_altitude_m = null,
  body,
  highlights: dayHighlights,
}: {
  tour_slug: string;
  day_number: number;
  title: string;
  route_from: string;
  route_to: string;
  distance_km: number | null;
  surface: string;
  max_altitude_m?: number | null;
  body: string;
  highlights: string[];
}): ItineraryDay {
  return {
    tour_slug,
    day_number,
    title: t(title),
    route_from,
    route_to,
    distance_km,
    surface: t(surface),
    max_altitude_m,
    body: t(body),
    highlights: highlights(dayHighlights),
  };
}

export const MOCK_TOURS: Tour[] = [
  {
    slug: "sobre-las-nubes",
    sort_order: 2,
    title: t("Sobre las Nubes"),
    slugs: {
      es: "sobre-las-nubes",
      en: "sobre-las-nubes",
      pt: "sobre-las-nubes",
    },
    region: t("Salta y Jujuy"),
    difficulty: "moderate",
    duration_days: 7,
    distance_km: 1712,
    ripio_percent: 50,
    max_altitude_m: 4895,
    base_price_usd: 0,
    currency: "USD",
    hero_image: "/images/tours/sobre_las_nubes/sobre_las_nubes_1_halftone.png",
    hero_image_color: "/images/tours/sobre_las_nubes/sobre_las_nubes_1_color.jpg",
    hero_image_drive_id: "",
    hero_image_color_drive_id: "",
    hero_image_alt: t("Ruta de montaña en Salta y Jujuy"),
    summary: t(
      "Siete días en moto cruzando Salta y Jujuy. Asfalto, ripio, altura, selva y pueblos andinos. El Abra del Acay marca la vara: 4895 msnm, una ruta que se gana kilómetro a kilómetro.",
    ),
    tagline: t("1712 km. 4895 msnm. Siete días sobre las nubes."),
    seo_title: empty,
    seo_description: t(
      "Siete días por Salta y Jujuy. 1712 km, 50% ripio y Abra del Acay a 4895 msnm con Moto On/Off.",
    ),
    published: true,
  },
  {
    slug: "volcanes-del-norte",
    sort_order: 1,
    title: t("Volcanes del Norte"),
    slugs: {
      es: "volcanes-del-norte",
      en: "volcanes-del-norte",
      pt: "volcanes-del-norte",
    },
    region: t("Catamarca"),
    difficulty: "intermediate_plus_plus",
    duration_days: 7,
    distance_km: 1917,
    ripio_percent: 50,
    max_altitude_m: 4550,
    base_price_usd: 0,
    currency: "USD",
    hero_image: "/images/tours/volcanes_del_norte/volcanes_del_norte_1_halftone.png",
    hero_image_color: "/images/tours/volcanes_del_norte/volcanes_del_norte_1_color.jpg",
    hero_image_drive_id: "",
    hero_image_color_drive_id: "",
    hero_image_alt: t("Paisaje volcánico de Catamarca"),
    summary: t(
      "Tour en moto por Catamarca\nCuestas Minas Capillitas, Balcón de Pissis, Campo de Piedra Pómez, salares, puna y volcanes. Una ruta de altura que alterna ripio, asfalto y jornadas para riders que ya saben lo que buscan.",
    ),
    tagline: t("Siete días entre volcanes, puna y caminos que ponen a prueba."),
    seo_title: empty,
    seo_description: t(
      "Tour de moto por Catamarca. Siete días, 50% ripio, volcanes, salares y altura con Moto On/Off.",
    ),
    published: true,
  },
  {
    slug: "cruces-del-sur",
    sort_order: 3,
    title: t("Cruces del Sur"),
    slugs: {
      es: "cruces-del-sur",
      en: "cruces-del-sur",
      pt: "cruces-del-sur",
    },
    region: t("Carretera Austral y Patagonia"),
    difficulty: "moderate",
    duration_days: 7,
    distance_km: 2321,
    ripio_percent: 45,
    max_altitude_m: null,
    base_price_usd: 0,
    currency: "USD",
    hero_image: "/images/tours/cruces_del_sur/cruces_del_sur_1_halftone.png",
    hero_image_color: "/images/tours/cruces_del_sur/cruces_del_sur_1_color.jpeg",
    hero_image_drive_id: "",
    hero_image_color_drive_id: "",
    hero_image_alt: t("Riders avanzando por un camino de ripio en Patagonia"),
    summary: t(
      "Carretera Austral en moto. Pasos fronterizos y ripio patagónico. 2321 km para cruzar bosques, lagos y rutas que se recuerdan por lo que exigieron.",
    ),
    tagline: t("2,321 km through Patagonia, lakes, and border crossings."),
    seo_title: empty,
    seo_description: t(
      "Tour de moto por Carretera Austral y Patagonia. Siete días, 2321 km y 45% ripio con Moto On/Off.",
    ),
    published: true,
  },
  {
    slug: "gigantes-del-oeste",
    sort_order: 4,
    title: t("Gigantes del Oeste"),
    slugs: {
      es: "gigantes-del-oeste",
      en: "gigantes-del-oeste",
      pt: "gigantes-del-oeste",
    },
    region: t("Mendoza a La Rioja"),
    difficulty: "moderate",
    duration_days: 8,
    distance_km: 2400,
    ripio_percent: 30,
    max_altitude_m: 4600,
    base_price_usd: 0,
    currency: "USD",
    hero_image: "/images/tours/gigantes_del_oeste/gigantes_del_oeste_1_halftone.png",
    hero_image_color: "/images/tours/gigantes_del_oeste/gigantes_del_oeste_1_color.jpg",
    hero_image_drive_id: "",
    hero_image_color_drive_id: "",
    hero_image_alt: t("Moto de aventura cruzando el oeste argentino"),
    summary: t(
      "Tour en moto por Mendoza, San Juan y La Rioja. Recorriendo la cordillera, Laguna Brava, Mina la Mejicana y caminos de montaña entre asfalto y ripio.",
    ),
    tagline: t("2400 km. Ocho días. La cordillera se cruza arriba de la moto."),
    seo_title: empty,
    seo_description: t(
      "Ocho días de moto por Mendoza, San Juan y La Rioja. 2400 km, ripio, cordillera y parques nacionales con Moto On/Off.",
    ),
    published: true,
  },
];

export const MOCK_ITINERARY: ItineraryDay[] = [
  {
    tour_slug: "sobre-las-nubes",
    day_number: 1,
    title: t("Salta Capital → Cabra Corral → Cuesta del Obispo → Cachi"),
    route_from: "Salta Capital",
    route_to: "Cachi",
    distance_km: 270,
    surface: t("70% asfalto"),
    max_altitude_m: 3300,
    body: t(
      "El primer día combina agua, selva, altura, montaña y pueblos andinos. Partimos desde Salta Capital rumbo al Embalse Cabra Corral, almorzamos con vistas al lago y seguimos hacia la Cuesta del Obispo. Curvas, cardones y nubes marcan la entrada a Cachi.",
    ),
    highlights: {
      es: [
        "Embalse Cabra Corral",
        "Parque Nacional Los Cardones",
        "Cuesta del Obispo",
        "Recta del Tintín",
      ],
      en: [
        "Embalse Cabra Corral",
        "Parque Nacional Los Cardones",
        "Cuesta del Obispo",
        "Recta del Tintín",
      ],
      pt: [
        "Embalse Cabra Corral",
        "Parque Nacional Los Cardones",
        "Cuesta del Obispo",
        "Recta del Tintín",
      ],
    },
  },
  {
    tour_slug: "sobre-las-nubes",
    day_number: 2,
    title: t("Cachi → Quebrada de las Flechas → Cafayate → El Carril"),
    route_from: "Cachi",
    route_to: "El Carril",
    distance_km: 308,
    surface: t("80% asfalto"),
    max_altitude_m: null,
    body: t(
      "Un recorrido pensado para disfrutar arriba de la moto. Curvas entretenidas, cambios de ritmo y una paleta de colores en todo el trayecto. Atravesamos la Quebrada de las Flechas, almorzamos en Cafayate y rodamos la Quebrada de las Conchas hasta El Carril.",
    ),
    highlights: {
      es: [
        "Quebrada de las Flechas",
        "Anfiteatro",
        "Quebrada de las Conchas",
        "Garganta del Diablo",
      ],
      en: [
        "Quebrada de las Flechas",
        "Anfiteatro",
        "Quebrada de las Conchas",
        "Garganta del Diablo",
      ],
      pt: [
        "Quebrada de las Flechas",
        "Anfiteatro",
        "Quebrada de las Conchas",
        "Garganta del Diablo",
      ],
    },
  },
  {
    tour_slug: "sobre-las-nubes",
    day_number: 3,
    title: t("El Carril → Abra del Acay → San Antonio de los Cobres"),
    route_from: "El Carril",
    route_to: "San Antonio de los Cobres",
    distance_km: null,
    surface: t("20% asfalto"),
    max_altitude_m: 4895,
    body: t(
      "El Abra del Acay es el tramo más emblemático de la Ruta 40: el punto más alto de esa ruta y de cualquier ruta nacional de América. La subida entrega color, acantilados y una montaña que exige atención. La bajada hacia San Antonio de los Cobres abre el paisaje y afloja el ritmo.",
    ),
    highlights: {
      es: ["Abra del Acay"],
      en: ["Abra del Acay"],
      pt: ["Abra del Acay"],
    },
  },
  {
    tour_slug: "sobre-las-nubes",
    day_number: 4,
    title: t("S.A. Cobres → Viaducto la Polvorilla → Tilcara"),
    route_from: "San Antonio de los Cobres",
    route_to: "Tilcara",
    distance_km: 293,
    surface: t("80% asfalto"),
    max_altitude_m: 3890,
    body: t(
      "Salimos rumbo al Viaducto La Polvorilla, pasando por La Juguetería y sus rocas inmensas. Seguimos hacia Salinas Grandes. En el descenso a Purmamarca aparecen curvas más marcadas, cerros de colores y la llegada al corazón de la quebrada.",
    ),
    highlights: {
      es: ["Viaducto la Polvorilla", "La Juguetería", "Salinas Grandes", "Cerro de los 7 colores"],
      en: ["Viaducto la Polvorilla", "La Juguetería", "Salinas Grandes", "Cerro de los 7 colores"],
      pt: ["Viaducto la Polvorilla", "La Juguetería", "Salinas Grandes", "Cerro de los 7 colores"],
    },
  },
  {
    tour_slug: "sobre-las-nubes",
    day_number: 5,
    title: t("Tilcara → Hornocal → Caspala"),
    route_from: "Tilcara",
    route_to: "Caspala",
    distance_km: 140,
    surface: t("20% asfalto"),
    max_altitude_m: 4550,
    body: t(
      "Día de conducción y entorno más que velocidad. Curvas cerradas, rectas con acantilados y caminos de altura poco transitados. Más que conducir la moto, se rueda flotando sobre las nubes.",
    ),
    highlights: {
      es: ["Hornocal", "Abra Azul", "Caspala"],
      en: ["Hornocal", "Abra Azul", "Caspala"],
      pt: ["Hornocal", "Abra Azul", "Caspala"],
    },
  },
  {
    tour_slug: "sobre-las-nubes",
    day_number: 6,
    title: t("Caspala → Parque Nacional Calilegua → Libertador San Martín"),
    route_from: "Caspala",
    route_to: "Libertador San Martín",
    distance_km: 205,
    surface: t("50% asfalto"),
    max_altitude_m: null,
    body: t(
      "El paisaje cambia por completo: de caminos de altura y pueblos aislados empezás a descender hacia la selva de las Yungas. La ruta se vuelve verde, húmeda, cerrada. Una transición ganada entre montaña árida y selva viva.",
    ),
    highlights: {
      es: ["Parque Nacional Calilegua"],
      en: ["Parque Nacional Calilegua"],
      pt: ["Parque Nacional Calilegua"],
    },
  },
  {
    tour_slug: "sobre-las-nubes",
    day_number: 7,
    title: t("Libertador San Martín → Embalse Las Maderas → Salta"),
    route_from: "Libertador San Martín",
    route_to: "Salta Capital",
    distance_km: 143,
    surface: t("80% asfalto"),
    max_altitude_m: null,
    body: t(
      "Una jornada tranquila para cerrar el tour. Almuerzo junto al Dique La Ciénaga y unas dos horas finales de asfalto y curvas hasta volver a Salta Capital.",
    ),
    highlights: {
      es: ["Embalse Las Maderas", "Dique La Ciénaga"],
      en: ["Embalse Las Maderas", "Dique La Ciénaga"],
      pt: ["Embalse Las Maderas", "Dique La Ciénaga"],
    },
  },
];

MOCK_ITINERARY.push(
  itineraryDay({
    tour_slug: "gigantes-del-oeste",
    day_number: 1,
    title: "Mendoza Capital → Potrerillos → Villavicencio → Uspallata",
    route_from: "Mendoza Capital",
    route_to: "Uspallata",
    distance_km: 218,
    surface: "80% asfalto",
    body: "Partimos el tour en moto desde Mendoza Capital rumbo a Potrerillos entre túneles, curvas y embalses. Después entramos a la Reserva Natural Villavicencio: ripio, 365 curvas y llegada al histórico hotel antes de dormir en Uspallata.",
    highlights: ["Embalse Potrerillos", "Reserva Natural Villavicencio", "365 curvas"],
  }),
  itineraryDay({
    tour_slug: "gigantes-del-oeste",
    day_number: 2,
    title: "Uspallata → Paso Los Libertadores → Uspallata",
    route_from: "Uspallata",
    route_to: "Uspallata",
    distance_km: 313,
    surface: "90% asfalto",
    max_altitude_m: 3854,
    body: "Cruzamos la cordillera por el Paso Internacional Los Libertadores. Aconcagua, túneles de alta montaña y la bajada por los Caracoles hacen una jornada de Andes completa, con regreso a Uspallata por el Cristo Redentor.",
    highlights: ["Puente del Inca", "Aconcagua", "Cristo Redentor", "Cuesta Caracoles"],
  }),
  itineraryDay({
    tour_slug: "gigantes-del-oeste",
    day_number: 3,
    title: "Pampa del Leoncito → Laguna Blanca → Calingasta",
    route_from: "Uspallata",
    route_to: "Calingasta",
    distance_km: 290,
    surface: "80% asfalto",
    body: "Dejamos el valle mendocino para entrar en planicies abiertas y caminos solitarios. El tour en moto sigue por Pampa del Leoncito, Barreal y Laguna Blanca: un día de horizontes largos y atardeceres ganados.",
    highlights: ["Pampa Leoncito", "Barreal", "Laguna Blanca"],
  }),
  itineraryDay({
    tour_slug: "gigantes-del-oeste",
    day_number: 4,
    title: "Barreal → Rodeo → Jáchal → Huaco → Villa Unión",
    route_from: "Barreal",
    route_to: "Villa Unión",
    distance_km: 437,
    surface: "100% asfalto",
    body: "Una etapa escénica que conecta valles, diques, quebradas y zonas áridas riojanas. Cuesta del Viento, Jáchal y Huaco cambian el ritmo con curvas cerradas y miradores abiertos.",
    highlights: ["Cuesta del Viento", "Quebrada de Jáchal", "Cuesta de Huaco"],
  }),
  itineraryDay({
    tour_slug: "gigantes-del-oeste",
    day_number: 5,
    title: "Villa Unión → Laguna Brava → Volcancito de Troya → Villa Unión",
    route_from: "Villa Unión",
    route_to: "Villa Unión",
    distance_km: 370,
    surface: "40% asfalto",
    max_altitude_m: 4300,
    body: "Subimos a Laguna Brava en moto, una laguna de alta montaña custodiada por silencio, flamencos y refugios de piedra. El ripio de Quebrada de la Troya y La Herradura pone color y exigencia al día.",
    highlights: ["Laguna Brava", "Volcancito de Troya", "Quebrada de la Troya", "La Herradura"],
  }),
  itineraryDay({
    tour_slug: "gigantes-del-oeste",
    day_number: 6,
    title: "Villa Unión → Talampaya → Valle de la Luna → Chilecito",
    route_from: "Villa Unión",
    route_to: "Chilecito",
    distance_km: 386,
    surface: "90% asfalto",
    body: "Talampaya abre paredones rojos y cañones de millones de años. Después el Valle de la Luna y la Cuesta de Miranda completan una jornada de colores duros antes de llegar a Chilecito.",
    highlights: ["Talampaya", "Valle de la Luna", "Cuesta de Miranda"],
  }),
  itineraryDay({
    tour_slug: "gigantes-del-oeste",
    day_number: 7,
    title: "Chilecito → Cañón del Ocre → Mina La Mejicana → Chilecito",
    route_from: "Chilecito",
    route_to: "Chilecito",
    distance_km: 240,
    surface: "20% asfalto",
    max_altitude_m: 4600,
    body: "El ascenso a Mina La Mejicana en moto es corto en kilómetros e intenso en historia, altura y paisaje. Cañón del Ocre, ríos anaranjados, estructuras abandonadas y silencio absoluto cierran el tramo más alto del tour.",
    highlights: ["Cañón del Ocre", "Mina La Mejicana", "Los Pesebres"],
  }),
  itineraryDay({
    tour_slug: "gigantes-del-oeste",
    day_number: 8,
    title: "Chilecito → Termas de Santa Teresita → La Rioja",
    route_from: "Chilecito",
    route_to: "La Rioja",
    distance_km: 311,
    surface: "100% asfalto",
    body: "Cerramos por Ruta 40 hacia las Termas de Santa Teresita. Una jornada de regreso y descanso antes de completar la llegada a La Rioja.",
    highlights: ["Ruta 40", "Termas de Santa Teresita", "La Rioja"],
  }),
  itineraryDay({
    tour_slug: "volcanes-del-norte",
    day_number: 1,
    title: "San Fernando → Fiambalá",
    route_from: "San Fernando",
    route_to: "Fiambalá",
    distance_km: 325,
    surface: "100% asfalto",
    body: "Atravesamos la Ruta del Adobe entre Tinogasta y Fiambalá. Pueblos chicos, precordillera árida y cierre en las Termas de Fiambalá para preparar la altura que viene.",
    highlights: ["Ruta del Adobe", "Tinogasta", "Termas de Fiambalá"],
  }),
  itineraryDay({
    tour_slug: "volcanes-del-norte",
    day_number: 2,
    title: "Fiambalá → Balcón del Pissis → Fiambalá",
    route_from: "Fiambalá",
    route_to: "Fiambalá",
    distance_km: 280,
    surface: "70% asfalto / 30% ripio",
    max_altitude_m: 4500,
    body: "La Ruta de los Seismiles entra por Quebrada de las Angosturas y gana altura hasta el Balcón del Pissis. Volcanes, lagunas y una vista monumental ponen la vara del viaje.",
    highlights: ["Balcón de Pissis", "Quebrada de las Angosturas", "Ruta de los Seismiles"],
  }),
  itineraryDay({
    tour_slug: "volcanes-del-norte",
    day_number: 3,
    title: "Fiambalá → Dunas de Tatón → Belén",
    route_from: "Fiambalá",
    route_to: "Belén",
    distance_km: 287,
    surface: "100% asfalto",
    body: "Rumbo norte hacia las Dunas de Tatón, uno de los campos de arena más aislados de Catamarca. Tinogasta, bodega Veralma y el km 4040 de la Ruta 40 marcan el camino a Belén.",
    highlights: ["Dunas de Tatón", "Tinogasta", "Km 4040", "Belén"],
  }),
  itineraryDay({
    tour_slug: "volcanes-del-norte",
    day_number: 4,
    title: "Belén → Antofagasta de la Sierra",
    route_from: "Belén",
    route_to: "Antofagasta de la Sierra",
    distance_km: 259,
    surface: "90% asfalto / 10% ripio",
    max_altitude_m: 3500,
    body: "La ruta a Antofagasta combina montaña, quebradas y puna abierta. Al superar la cuesta aparecen volcanes, silencio y el campo de lava del Volcán Alumbrera.",
    highlights: ["Cuesta de Randolfo", "Pucará La Alumbrera", "Campos de lava"],
  }),
  itineraryDay({
    tour_slug: "volcanes-del-norte",
    day_number: 5,
    title: "Antofagasta de la Sierra → Campo de Piedra Pómez",
    route_from: "Antofagasta de la Sierra",
    route_to: "Antofagasta de la Sierra",
    distance_km: 200,
    surface: "30% asfalto / 70% ripio",
    max_altitude_m: 3500,
    body: "El terreno se vuelve claro, volcánico y ondulado hasta entrar al Campo de Piedra Pómez. Después la Laguna Carachi Pampa abre una puna inmensa, solitaria y difícil de olvidar.",
    highlights: ["Campo de Piedra Pómez", "Laguna Carachi Pampa", "Volcán Carachi Pampa"],
  }),
  itineraryDay({
    tour_slug: "volcanes-del-norte",
    day_number: 6,
    title: "El Peñón → Andalgalá",
    route_from: "El Peñón",
    route_to: "Andalgalá",
    distance_km: 340,
    surface: "50% asfalto / 50% ripio",
    body: "Saliendo de El Peñón, el paisaje volcánico da paso a caminos de montaña. Cuesta de Capillitas y Refugio del Minero hacen un día de ripio, altura y descenso hacia Andalgalá.",
    highlights: ["Cuesta Minas Capillitas", "Refugio del Minero", "Andalgalá"],
  }),
  itineraryDay({
    tour_slug: "volcanes-del-norte",
    day_number: 7,
    title: "Andalgalá → San Fernando",
    route_from: "Andalgalá",
    route_to: "San Fernando",
    distance_km: 226,
    surface: "70% asfalto / 30% ripio",
    body: "El cierre cambia otra vez el clima: cursos de agua, vegetación densa y selva de montaña. Cuesta la Chilca y Loma Larga devuelven la ruta a San Fernando.",
    highlights: ["Cuesta la Chilca", "Loma Larga", "San Fernando"],
  }),
  itineraryDay({
    tour_slug: "cruces-del-sur",
    day_number: 1,
    title: "Bariloche → Trevelin",
    route_from: "Bariloche",
    route_to: "Trevelin",
    distance_km: 306,
    surface: "30% ripio",
    body: "Salimos desde Bariloche por Ruta 40 y entramos en ritmo entre asfalto y ripio. El desvío por Cholila abre el Parque Nacional Los Alerces antes de llegar a Trevelin.",
    highlights: ["El Bolsón", "Lago Puelo", "Parque Nacional Los Alerces"],
  }),
  itineraryDay({
    tour_slug: "cruces-del-sur",
    day_number: 2,
    title: "Trevelin → Paso Futaleufú → Puerto Cisnes",
    route_from: "Trevelin",
    route_to: "Puerto Cisnes",
    distance_km: 325,
    surface: "20% ripio",
    body: "Campo de tulipanes, Paso Futaleufú y entrada plena a la Carretera Austral. Bosque cerrado, ríos, curvas y montaña hasta cerrar el día en Puerto Cisnes.",
    highlights: ["Campo de Tulipanes", "Paso Futaleufú", "Termas Ventisquero", "Puerto Cisnes"],
  }),
  itineraryDay({
    tour_slug: "cruces-del-sur",
    day_number: 3,
    title: "Puerto Cisnes → Puerto Ingeniero Ibáñez → Chile Chico",
    route_from: "Puerto Cisnes",
    route_to: "Chile Chico",
    distance_km: 322,
    surface: "20% ripio",
    body: "Montaña, fiordos, asfalto y ripio hacia Puerto Ingeniero Ibáñez. La barcaza cruza el Lago General Carrera y deja la ruta lista para entrar a Chile Chico.",
    highlights: ["Reserva Nacional Mañihuales", "Cerro Castillo", "Ferry Lago General Carrera"],
  }),
  itineraryDay({
    tour_slug: "cruces-del-sur",
    day_number: 4,
    title: "Chile Chico → Cochrane",
    route_from: "Chile Chico",
    route_to: "Cochrane",
    distance_km: 178,
    surface: "70% ripio",
    body: "Día de ripio real bordeando el Lago General Carrera. Agua, montaña y camino abierto acompañan una de las etapas más auténticas de la Carretera Austral.",
    highlights: ["Lago General Carrera", "Reserva Nacional Lago General Carrera", "Lago Bertrand"],
  }),
  itineraryDay({
    tour_slug: "cruces-del-sur",
    day_number: 5,
    title: "Cochrane → Paso Roballos → Perito Moreno",
    route_from: "Cochrane",
    route_to: "Perito Moreno",
    distance_km: 250,
    surface: "80% ripio",
    body: "Paso Roballos entrega estepa abierta, cordillera a los costados y aislamiento total. Del lado argentino, el camino bordea los Andes antes de llegar a Los Antiguos y Perito Moreno.",
    highlights: ["Valle Chacabuco", "Paso Roballos", "Lago Cochrane", "Los Antiguos"],
  }),
  itineraryDay({
    tour_slug: "cruces-del-sur",
    day_number: 6,
    title: "Perito Moreno → Lago Vintter",
    route_from: "Perito Moreno",
    route_to: "Lago Vintter",
    distance_km: 473,
    surface: "15% ripio",
    body: "Jornada larga de regreso por Ruta 40, con rectas aisladas hasta Gobernador Costa. Después tomamos camino secundario hacia Río Pico y Lago Vintter, una Patagonia menos vista.",
    highlights: ["Ruta 40", "Río Pico", "Lago Vintter"],
  }),
  itineraryDay({
    tour_slug: "cruces-del-sur",
    day_number: 7,
    title: "Lago Vintter → Bariloche",
    route_from: "Lago Vintter",
    route_to: "Bariloche",
    distance_km: 467,
    surface: "35% ripio",
    body: "Bosques bajos, montañas nevadas y ripio sin tránsito hasta Trevelin. Después volvemos a enlazar Ruta 40, El Bolsón y Bariloche para cerrar el cruce patagónico.",
    highlights: ["Lago Vintter", "Lago Palena", "Ruta 40", "Bariloche"],
  }),
);

export const MOCK_TOUR_SECTIONS: TourSection[] = [
  "Traslado de la moto ida y vuelta a destino",
  "Seguro de carga de la moto",
  "Refrigerios",
  "Moto de repuesto",
  "Starlink",
  "Siete noches de alojamiento en hospedajes seleccionados",
  "Vehículo de apoyo durante toda la ruta",
  "Combustible de emergencia para todo el trayecto",
  "Desayunos, almuerzos y cenas",
  "Guía con experiencia probada en el oeste argentino",
].map((text, index) => ({
  tour_slug: "sobre-las-nubes",
  type: "included",
  sort_order: index + 1,
  text: t(text),
}));

MOCK_TOUR_SECTIONS.push(
  ...[
    "Pasajes aéreos hasta Salta y desde Salta",
    "Bebidas alcohólicas y comidas fuera del itinerario",
    "Seguro de viajero con cobertura de moto",
    "Alquiler de moto si no traés la tuya",
  ].map((text, index) => ({
    tour_slug: "sobre-las-nubes",
    type: "not_included" as const,
    sort_order: index + 1,
    text: t(text),
  })),
  ...[
    "Cupo limitado por tour.",
    "Esta travesía atraviesa altura sostenida (2500–4550 msnm).",
    "Se requiere experiencia previa en ripio.",
  ].map((text, index) => ({
    tour_slug: "sobre-las-nubes",
    type: "need_to_know" as const,
    sort_order: index + 1,
    text: t(text),
  })),
);

MOCK_TOUR_SECTIONS.push(
  ...[
    "Traslado de la moto ida y vuelta a destino",
    "Seguro de carga de la moto",
    "Refrigerios",
    "Moto de repuesto",
    "Starlink",
    "Siete noches de alojamiento en hospedajes seleccionados",
    "Vehículo de apoyo durante toda la ruta",
    "Combustible de emergencia para todo el trayecto",
    "Desayunos, almuerzos y cenas",
    "Guía con experiencia probada en el oeste argentino",
  ].map((text, index) => ({
    tour_slug: "volcanes-del-norte",
    type: "included" as const,
    sort_order: index + 1,
    text: t(text),
  })),
  ...[
    "Pasajes aéreos hasta Catamarca y desde Catamarca",
    "Bebidas alcohólicas y comidas fuera del itinerario",
    "Seguro de viajero con cobertura de moto",
    "Alquiler de moto si no traés la tuya",
  ].map((text, index) => ({
    tour_slug: "volcanes-del-norte",
    type: "not_included" as const,
    sort_order: index + 1,
    text: t(text),
  })),
  ...[
    "Cupo limitado por tour.",
    "Esta travesía atraviesa altura sostenida (2500–4550 msnm).",
    "Se requiere experiencia previa en ripio.",
  ].map((text, index) => ({
    tour_slug: "volcanes-del-norte",
    type: "need_to_know" as const,
    sort_order: index + 1,
    text: t(text),
  })),
);

MOCK_TOUR_SECTIONS.push(
  ...[
    "Traslado de la moto ida y vuelta a destino",
    "Seguro de carga de la moto",
    "Refrigerios",
    "Moto de repuesto",
    "Starlink",
    "Siete noches de alojamiento en hospedajes seleccionados",
    "Vehículo de apoyo durante toda la ruta",
    "Combustible de emergencia para todo el trayecto",
    "Desayunos, almuerzos y cenas",
    "Guía con experiencia probada en el oeste argentino",
  ].map((text, index) => ({
    tour_slug: "gigantes-del-oeste",
    type: "included" as const,
    sort_order: index + 1,
    text: t(text),
  })),
  ...[
    "Pasajes aéreos hasta Mendoza y desde La Rioja",
    "Bebidas alcohólicas y comidas fuera del itinerario",
    "Seguro de viajero con cobertura de moto",
    "Alquiler de moto si no traés la tuya",
  ].map((text, index) => ({
    tour_slug: "gigantes-del-oeste",
    type: "not_included" as const,
    sort_order: index + 1,
    text: t(text),
  })),
  ...[
    "Cupo limitado por tour.",
    "El tour cruza dos veces la frontera Argentina-Chile. DNI o pasaporte vigente y permiso para circular si la moto no está a tu nombre. Te asesoramos antes del viaje.",
    "Se requiere experiencia previa en ripio.",
  ].map((text, index) => ({
    tour_slug: "gigantes-del-oeste",
    type: "need_to_know" as const,
    sort_order: index + 1,
    text: t(text),
  })),
);

export const MOCK_GALLERY: GalleryImage[] = [
  galleryImage({
    tour_slug: "sobre-las-nubes",
    sort_order: 1,
    image_url: "/images/tours/sobre_las_nubes/20260311_100314.jpg",
    alt: "Camino de altura en la ruta Sobre las Nubes",
    featured: true,
  }),
  galleryImage({
    tour_slug: "sobre-las-nubes",
    sort_order: 2,
    image_url: "/images/tours/sobre_las_nubes/20260311_141800.jpg",
    alt: "Moto avanzando por caminos de Salta y Jujuy",
  }),
  galleryImage({
    tour_slug: "sobre-las-nubes",
    sort_order: 3,
    image_url: "/images/tours/sobre_las_nubes/20260402_180621.jpg",
    alt: "Ruta andina con cerros y ripio en Sobre las Nubes",
  }),
  galleryImage({
    tour_slug: "sobre-las-nubes",
    sort_order: 4,
    image_url: "/images/tours/sobre_las_nubes/20260226_200924.jpg",
    alt: "Trazado de montaña ganado sobre la puna",
  }),
  galleryImage({
    tour_slug: "sobre-las-nubes",
    sort_order: 5,
    image_url: "/images/tours/sobre_las_nubes/20251109_101738.jpg",
    alt: "Camino abierto entre valles del norte argentino",
  }),
  galleryImage({
    tour_slug: "sobre-las-nubes",
    sort_order: 6,
    image_url: "/images/tours/sobre_las_nubes/2.jpg",
    alt: "Ruta de ripio entre Salta y Jujuy",
  }),
  galleryImage({
    tour_slug: "sobre-las-nubes",
    sort_order: 7,
    image_url: "/images/tours/sobre_las_nubes/3.jpg",
    alt: "Paso de montaña en la ruta Sobre las Nubes",
  }),
  galleryImage({
    tour_slug: "sobre-las-nubes",
    sort_order: 8,
    image_url: "/images/tours/sobre_las_nubes/4.jpg",
    alt: "Rider enfrentando curvas de altura en el norte",
  }),
  galleryImage({
    tour_slug: "sobre-las-nubes",
    sort_order: 9,
    image_url: "/images/tours/sobre_las_nubes/5.jpg",
    alt: "Paisaje de altura recorrido sobre dos ruedas",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 1,
    image_url: "/images/tours/gigantes_del_oeste/20231105_141145.jpg",
    alt: "Moto cruzando caminos de montaña entre Mendoza y La Rioja",
    featured: true,
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 2,
    image_url: "/images/tours/gigantes_del_oeste/20231105_160041.jpg",
    alt: "Ruta de cordillera en Gigantes del Oeste",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 3,
    image_url: "/images/tours/gigantes_del_oeste/gigantes-fotos-caco/DIA%203.png",
    alt: "Motos avanzando por planicies abiertas en Gigantes del Oeste",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 4,
    image_url: "/images/tours/gigantes_del_oeste/20220909_151413.jpg",
    alt: "Rider avanzando por el ripio cuyano",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 5,
    image_url: "/images/tours/gigantes_del_oeste/20220909_153529.jpg",
    alt: "Ruta abierta entre montañas del oeste",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 6,
    image_url: "/images/tours/gigantes_del_oeste/20220430_170600.jpg",
    alt: "Camino de alta montaña recorrido en moto",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 7,
    image_url: "/images/tours/gigantes_del_oeste/IMG-20260405-WA0059.jpg",
    alt: "Moto cargada para cruzar el oeste argentino",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 8,
    image_url: "/images/tours/gigantes_del_oeste/IMG-20260405-WA0070.jpg",
    alt: "Rider en una jornada larga de montaña",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 9,
    image_url: "/images/tours/gigantes_del_oeste/IMG-20260421-WA0096.jpg",
    alt: "Moto detenida en una ruta de ripio",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 10,
    image_url: "/images/tours/gigantes_del_oeste/IMG-20260421-WA0100.jpg",
    alt: "Camino conquistado en la ruta Gigantes del Oeste",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 11,
    image_url: "/images/tours/gigantes_del_oeste/IMG-20260421-WA0103.jpg",
    alt: "Trazado de ripio entre sierras y cordillera",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 12,
    image_url: "/images/tours/gigantes_del_oeste/IMG-20260423-WA0022.jpg",
    alt: "Rider y moto en el oeste argentino",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 13,
    image_url: "/images/tours/gigantes_del_oeste/motion_photo_1364649692705347634.jpg",
    alt: "Camino de montaña puesto a prueba por la ruta",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 14,
    image_url: "/images/tours/gigantes_del_oeste/motion_photo_3144126936191235939.jpg",
    alt: "Paisaje de cordillera atravesado en moto",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 15,
    image_url: "/images/tours/gigantes_del_oeste/gigantes-fotos-caco/DIA%202.jpg",
    alt: "Camino de alta montaña durante el día dos de Gigantes del Oeste",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 16,
    image_url: "/images/tours/gigantes_del_oeste/gigantes-fotos-caco/DIA%204.png",
    alt: "Riders avanzando por planicies de ripio en Gigantes del Oeste",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 17,
    image_url: "/images/tours/gigantes_del_oeste/gigantes-fotos-caco/DIA%205.jpg",
    alt: "Moto sobre camino abierto rumbo a Laguna Brava",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 18,
    image_url: "/images/tours/gigantes_del_oeste/gigantes-fotos-caco/DIA%207.jpg",
    alt: "Estructura minera en la ruta hacia Mina La Mejicana",
  }),
  galleryImage({
    tour_slug: "gigantes-del-oeste",
    sort_order: 19,
    image_url: "/images/tours/gigantes_del_oeste/gigantes-fotos-caco/Galeria%20foto%206.jpg",
    alt: "Grupo de motos detenido en un camino de montaña del oeste argentino",
  }),
  galleryImage({
    tour_slug: "volcanes-del-norte",
    sort_order: 1,
    image_url: "/images/tours/volcanes_del_norte/1.jpg",
    alt: "Ruta de Catamarca entre volcanes y puna",
    featured: true,
  }),
  galleryImage({
    tour_slug: "volcanes-del-norte",
    sort_order: 2,
    image_url: "/images/tours/volcanes_del_norte/2.jpg",
    alt: "Camino de altura en Volcanes del Norte",
  }),
  galleryImage({
    tour_slug: "volcanes-del-norte",
    sort_order: 3,
    image_url: "/images/tours/volcanes_del_norte/3.jpg",
    alt: "Paisaje volcánico cruzado en moto",
  }),
  galleryImage({
    tour_slug: "volcanes-del-norte",
    sort_order: 4,
    image_url: "/images/tours/volcanes_del_norte/4.JPG",
    alt: "Ruta de montaña en Catamarca",
  }),
  galleryImage({
    tour_slug: "volcanes-del-norte",
    sort_order: 5,
    image_url: "/images/tours/volcanes_del_norte/5.png",
    alt: "Camino de ripio entre volcanes del norte",
  }),
  galleryImage({
    tour_slug: "volcanes-del-norte",
    sort_order: 6,
    image_url: "/images/tours/volcanes_del_norte/6.jpg",
    alt: "Jornada de ruta larga sobre la puna catamarqueña",
  }),
  galleryImage({
    tour_slug: "volcanes-del-norte",
    sort_order: 7,
    image_url: "/images/tours/volcanes_del_norte/8.jpg",
    alt: "Horizonte de altura en Volcanes del Norte",
  }),
  galleryImage({
    tour_slug: "volcanes-del-norte",
    sort_order: 8,
    image_url: "/images/tours/volcanes_del_norte/9.jpg",
    alt: "Ruta abierta entre salares y volcanes",
  }),
  galleryImage({
    tour_slug: "volcanes-del-norte",
    sort_order: 9,
    image_url: "/images/tours/volcanes_del_norte/11.jpeg",
    alt: "Moto sobre caminos probados de Catamarca",
  }),
  galleryImage({
    tour_slug: "cruces-del-sur",
    sort_order: 1,
    image_url: "/images/tours/cruces_del_sur/cruces-fotos-caco/Galeria%201.jpeg",
    alt: "Campo de Tulipanes, Trevelin.",
    featured: true,
  }),
  galleryImage({
    tour_slug: "cruces-del-sur",
    sort_order: 2,
    image_url: "/images/tours/cruces_del_sur/2.jpg",
    alt: "Camino ripio, Carretera Austral",
  }),
  galleryImage({
    tour_slug: "cruces-del-sur",
    sort_order: 3,
    image_url: "/images/tours/cruces_del_sur/cruces-fotos-caco/Dia%203.png",
    alt: "Descanso entre la ruta 40 y la Carretera Austral",
  }),
  galleryImage({
    tour_slug: "cruces-del-sur",
    sort_order: 4,
    image_url: "/images/tours/cruces_del_sur/cruces-fotos-caco/Dia%204.jpg",
    alt: "Camino a Puerto Cisnes, Chile",
  }),
  galleryImage({
    tour_slug: "cruces-del-sur",
    sort_order: 5,
    image_url: "/images/tours/cruces_del_sur/5.png",
    alt: "Paisaje de Patagonia ganado sobre ripio",
  }),
  galleryImage({
    tour_slug: "cruces-del-sur",
    sort_order: 6,
    image_url: "/images/tours/cruces_del_sur/6.jpg",
    alt: "Camino abierto entre bosques y lagos patagónicos",
  }),
  galleryImage({
    tour_slug: "cruces-del-sur",
    sort_order: 7,
    image_url: "/images/tours/cruces_del_sur/cruces-fotos-caco/Dia%207.jpg",
    alt: "Ruta 40, ripio hacia Chile",
  }),
  galleryImage({
    tour_slug: "cruces-del-sur",
    sort_order: 8,
    image_url: "/images/tours/cruces_del_sur/8.png",
    alt: "Vista a volcán en la Carretera Austral",
  }),
  galleryImage({
    tour_slug: "cruces-del-sur",
    sort_order: 9,
    image_url: "/images/tours/cruces_del_sur/cruces-fotos-caco/Galeria%209.png",
    alt: "Cruce de frontera hacia Chile",
  }),
  galleryImage({
    tour_slug: "cruces-del-sur",
    sort_order: 10,
    image_url: "/images/tours/cruces_del_sur/cruces-fotos-caco/Galeria%2010.jpeg",
    alt: "Paso Roballos en moto, Argentina",
  }),
  galleryImage({
    tour_slug: "cruces-del-sur",
    sort_order: 11,
    image_url: "/images/tours/cruces_del_sur/cruces-fotos-caco/Galeria%2011.jpg",
    alt: "Paso Roballos en moto, Argentina",
  }),
];

export const MOCK_DEPARTURES: Departure[] = [
  {
    tour_slug: "sobre-las-nubes",
    start_date: "2026-08-01",
    end_date: "2026-08-07",
    capacity: 8,
    spots_remaining: 8,
    status: "open",
    price: 0,
    currency: "USD",
    notes: t("Abra del Acay, Quebrada de las Flechas y 1712 km ganados en el NOA."),
  },
  {
    tour_slug: "volcanes-del-norte",
    start_date: "2026-09-12",
    end_date: "2026-09-18",
    capacity: 8,
    spots_remaining: 8,
    status: "open",
    price: 0,
    currency: "USD",
    notes: t("Catamarca alta: volcanes, puna, salares y jornadas largas de ripio."),
  },
  {
    tour_slug: "cruces-del-sur",
    start_date: "2026-11-07",
    end_date: "2026-11-13",
    capacity: 8,
    spots_remaining: 8,
    status: "open",
    price: 0,
    currency: "USD",
    notes: t("Patagonia y Carretera Austral con bosque, frontera y ripio."),
  },
];
